// <auto-generated />
using System;
using CPUModule.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CPUModule.Infrastructure.Migrations
{
    [DbContext(typeof(CpuDbContext))]
    partial class CpuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("CPU")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CPUModule.Domain.Entities.CPUProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArchitectureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseClockGHz")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BoostClockGHz")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("CoolerIncluded")
                        .HasColumnType("bit");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HasIntegratedGraphics")
                        .HasColumnType("bit");

                    b.Property<string>("IncludedCoolerType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IntegratedGraphicsModel")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("L2CacheMB")
                        .HasColumnType("int");

                    b.Property<int>("L3CacheMB")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaxMemoryCapacityGB")
                        .HasColumnType("int");

                    b.Property<int>("MaxMemorySpeedMHz")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PCIeLanes")
                        .HasColumnType("int");

                    b.Property<string>("PCIeVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<Guid>("SocketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupportedRamType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("SupportsOverclocking")
                        .HasColumnType("bit");

                    b.Property<int>("TDPWatts")
                        .HasColumnType("int");

                    b.Property<int>("Threads")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectureId");

                    b.HasIndex("SocketId");

                    b.ToTable("CPUProfiles", "CPU");
                });

            modelBuilder.Entity("Domain.Entities.CPU.CPUArchitecture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProcessNodeNM")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CPUArchitectures", "CPU");
                });

            modelBuilder.Entity("Domain.Entities.Socket.SocketProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SocketProfile", "CPU");
                });

            modelBuilder.Entity("CPUModule.Domain.Entities.CPUProfile", b =>
                {
                    b.HasOne("Domain.Entities.CPU.CPUArchitecture", "Architecture")
                        .WithMany()
                        .HasForeignKey("ArchitectureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Socket.SocketProfile", null)
                        .WithMany()
                        .HasForeignKey("SocketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CPUModule.Domain.Primitives.ValueObjects.CPUCores", "Cores", b1 =>
                        {
                            b1.Property<Guid>("CPUProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("EfficiencyCores")
                                .HasColumnType("int")
                                .HasColumnName("EfficiencyCores");

                            b1.Property<int>("PerformanceCores")
                                .HasColumnType("int")
                                .HasColumnName("PerformanceCores");

                            b1.HasKey("CPUProfileId");

                            b1.ToTable("CPUProfiles", "CPU");

                            b1.WithOwner()
                                .HasForeignKey("CPUProfileId");
                        });

                    b.Navigation("Architecture");

                    b.Navigation("Cores")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
